baseURL: https://website.doocrate.com/
languageCode: en-us
title: Doocrate - Co-Creation events
theme: hugo-fresh

params:
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Doocrate. Co-Create.
    # Hero subtitle (optional)
    subtitle: Co-Create event management platform
    # Button text
    buttontext: Get started
    # Where the main hero button links to
    buttonlink: "https://doocrate.com"
    # Hero image (from /images/___)
    image: illustrations/worker.svg
    # Footer logos (from /images/logos/clients/___)
    clientlogos:
    - burnerot.png
    - leamons.jpg
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Why
    url: /#why
  - title: Features
    url: /#features
  - title: Clients
    url: /#clients
  - title: Start project
    url: https://doocrate.com
    button: true
  section1:
    name: why
    title: Why Doocrate
    subtitle: 
    tiles:
    - title: Event managment
      icon: calendar-alt
      text: Track your community tasks in a single place
      url: https://doocrate.com
      buttonText: Get started
    - title: Doocracy
      icon: laptop-cloud
      text: Unleash your community creativity by allowing them to choose roles and tasks for themself and execute them.
      url: https://doocrate.com
      buttonText: Get started
    - title: Open source
      icon: plug-cloud
      text: Doocrate is open source. We welcome contributions and supported by the community.
      url: https://github.com/metaburn/doocrate
      buttonText: Join
  section2:
    name: features
    title: Doocrate Features
    subtitle: Or how we co-manage our communities
    features:
    - title: Tasks - Flattened
      text: Categorize your task and then see all of them on a single page
      image: app-mockup-tasks.png
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Take responsibility for any task,
      text: All tasks are open for users to grab. Whenever a hero is taken responsibility the task is all hers.
      icon: doc-sync
      image: app-mockup-take-responsibility.png
    - title: Search by labels
      text: Filter tasks by labels
      icon: mobile-feed
      image: app-mockup-search.png
  section3:
    title: Doocrate
    subtitle: Some catching subtitle
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    name: clients
    title: Organizations Using Doocrate!
    subtitle: Here are what others have to say about doocrate
    clients:
    - name: Or Granot
      quote: Doocrate allowed our community to get transperency into the work
      job: Community Leader
      img: 1
    - name: Amir Shalem
      quote: Doocrate has sparked a new spirit in our community
      job: Community Leader
      img: 2
    - name: Gal Bracha
      quote: Doocrate allowed us to co-create in a flat non-heirecial way
      job: Open source developer
      img: 3
  footer:
    # Logo (from /images/logos/___)
    logo: doocrate-logo.png
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
      # Icons are from Font Awesome
    - link: https://github.com/metaburn/doocrate
      icon: github
    - link: https://www.facebook.com/metaburnorg/
      icon: facebook
    bulmalogo: false
    product:
    - text: Discover features
      link: /
    - text: Why choose our product?
      link: /
    - text: Compare features
      link: /
    - text: Our roadmap
      link: /
    - text: Request features
      link: /
    docs:
    - text: Get started
      link: /
    - text: User guides
      link: /
    - text: Admin guide
      link: /
    - text: Developers
      link: /
    blogroll:
    - text: Latest news
      link: /
    - text: Tech articles
      link: /
    - text: Video blog
      link: /
